import { Router } from "express";
import fs from "node:fs";
import path from "node:path";
import multer from "multer";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import { InvoiceStatus, InvoiceType, PatientDocumentKind, VisitStatus } from "@prisma/client";
import { prisma } from "../lib/db.js";
import {
  ALLOWED_MIME_TYPES,
  DOCUMENT_KIND_LABELS,
  MAX_FILE_SIZE_BYTES,
  UPLOADS_ROOT,
  backfillMissingDossiers,
  deleteDocumentFile,
  ensurePatientDossier,
  ensureUploadsRoot,
  patientUploadDir,
  sanitizeFileName,
} from "../lib/patient-dossier.js";
import {
  getMedecinDossierPatients,
  getPatientMedicalHistory,
  isAutoGeneratedLabDocument,
} from "../lib/patient-medical-record.js";
import {
  PATIENT_HAS_PAYMENTS_MESSAGE,
  assertPatientDataDeletable,
  patientHasPaidBilling,
} from "../lib/patient-payment-guard.js";
import { ensurePatientMergedByPhone } from "../lib/merge-patients.js";
import { buildPatientPaymentHistory } from "../lib/patient-invoice-payments.js";
import { medecinMatchWhere } from "../lib/medecin-queues.js";
import { resolveConsultationFeeForPatientDoctor } from "../lib/consultation-validity.js";
import {
  resolveConsultationBilling,
  shouldCreateImmediateInvoice,
} from "../lib/patient-billing.js";
import {
  archiveVisitsForReconsultation,
  planReconsultation,
} from "../lib/reconsultation.js";
import { generateInvoiceNumber } from "../lib/patient-code.js";
import {
  consultationInvoiceCreateData,
  consultationInvoiceUpdateData,
} from "../lib/consultation-invoice.js";
import { requireAnyModule, requireAuth, requireManageAccess } from "../middleware/auth.js";
import {
  canViewClinicalConsultationDetails,
  canWriteDossierDocuments,
  type AppUserRole,
} from "../lib/roles.js";

const router = Router();
router.use(requireAuth);

const DOSSIER_MODULES = ["dossier-patient"] as const;
const PAYMENT_HISTORY_MODULES = ["dossier-patient", "reception", "comptabilite"] as const;

const upload = multer({
  storage: multer.diskStorage({
    destination: async (req, _file, cb) => {
      try {
        const patientId = String(req.params.patientId);
        const dir = patientUploadDir(patientId);
        await fs.promises.mkdir(dir, { recursive: true });
        cb(null, dir);
      } catch (error) {
        cb(error as Error, "");
      }
    },
    filename: (_req, file, cb) => {
      const safe = sanitizeFileName(file.originalname);
      cb(null, `${Date.now()}-${randomUUID().slice(0, 8)}-${safe}`);
    },
  }),
  limits: { fileSize: MAX_FILE_SIZE_BYTES },
  fileFilter: (_req, file, cb) => {
    if (!ALLOWED_MIME_TYPES.has(file.mimetype)) {
      cb(new Error("Type de fichier non autorisé"));
      return;
    }
    cb(null, true);
  },
});

const uploadDocumentSchema = z.object({
  kind: z.nativeEnum(PatientDocumentKind),
  title: z.string().min(1).max(200),
  documentDate: z.string().min(1),
  visitId: z.string().optional(),
});

router.get("/kinds", (_req, res) => {
  res.json(
    Object.entries(DOCUMENT_KIND_LABELS).map(([value, label]) => ({ value, label })),
  );
});

router.get("/medecin/patients", requireAnyModule(...DOSSIER_MODULES), async (req, res) => {
  if (req.user!.role !== "MEDECIN") {
    return res.status(403).json({ error: "Réservé aux médecins" });
  }

  const patients = await getMedecinDossierPatients(req.user!.id);
  return res.json(patients);
});

router.get("/:patientId/payment-history", requireAnyModule(...PAYMENT_HISTORY_MODULES), async (req, res) => {
  const patientId = String(req.params.patientId);
  const patient = await prisma.patient.findUnique({
    where: { id: patientId },
    select: { id: true },
  });
  if (!patient) return res.status(404).json({ error: "Patient introuvable" });
  const history = await buildPatientPaymentHistory(patientId);
  return res.json(history);
});

router.get("/:patientId", requireAnyModule(...DOSSIER_MODULES), async (req, res) => {
  const rawPatientId = String(req.params.patientId);
  const merge = await ensurePatientMergedByPhone(rawPatientId);
  const patientId = merge.patientId;
  const kind = req.query.kind as PatientDocumentKind | undefined;

  const patient = await prisma.patient.findUnique({
    where: { id: patientId },
    select: {
      id: true,
      code: true,
      firstName: true,
      lastName: true,
      age: true,
      ageUnit: true,
      phone: true,
      gender: true,
      category: true,
      createdAt: true,
    },
  });

  if (!patient) return res.status(404).json({ error: "Patient introuvable" });

  const doctorScope = req.user!.role === "MEDECIN" ? req.user!.id : undefined;
  if (doctorScope) {
    const linkedToPatient = await prisma.visit.findFirst({
      where: { patientId, ...medecinMatchWhere(doctorScope) },
      select: { id: true },
    });
    if (!linkedToPatient) {
      return res.status(403).json({
        error: "Accès refusé — ce patient n'est pas suivi par votre compte.",
      });
    }
  }

  const canViewAllClinical = canViewClinicalConsultationDetails(req.user!.role);
  const medicalHistory = await getPatientMedicalHistory(patientId, {
    doctorScope,
    canViewAllClinicalDetails: canViewAllClinical,
    viewerDoctorId: req.user!.role === "MEDECIN" ? req.user!.id : null,
  });

  const dossier = await ensurePatientDossier(patientId);

  const allDocuments = await prisma.patientDocument.findMany({
    where: {
      dossierId: dossier.id,
      ...(kind ? { kind } : {}),
    },
    include: {
      uploadedBy: { select: { firstName: true, lastName: true } },
    },
    orderBy: [{ documentDate: "desc" }, { createdAt: "desc" }],
  });

  const documents = allDocuments.filter(
    (doc) => !isAutoGeneratedLabDocument(doc.fileName, doc.mimeType),
  );

  const countsByKind: Partial<Record<PatientDocumentKind, number>> = {};
  for (const doc of documents) {
    countsByKind[doc.kind] = (countsByKind[doc.kind] ?? 0) + 1;
  }

  const hasPaidBilling = await patientHasPaidBilling(patientId);

  let reconsult: {
    canReconsult: boolean;
    activeVisitId: string | null;
  } | null = null;

  if (req.user!.role === "MEDECIN") {
    const doctorId = req.user!.id;
    const activeVisit = await prisma.visit.findFirst({
      where: {
        patientId,
        status: { in: [VisitStatus.WAITING_CONSULTATION, VisitStatus.IN_CONSULTATION] },
        OR: [
          { assignedDoctorId: doctorId },
          { consultation: { is: { doctorId } } },
        ],
      },
      select: { id: true },
      orderBy: { updatedAt: "desc" },
    });
    reconsult = {
      canReconsult: true,
      activeVisitId: activeVisit?.id ?? null,
    };
  }

  return res.json({
    patient,
    dossier: { id: dossier.id, createdAt: dossier.createdAt },
    documents,
    medicalHistory,
    countsByKind,
    dataProtection: {
      hasPaidBilling,
      canDeleteDocuments: !hasPaidBilling,
    },
    reconsult,
  });
});

/** Reconsultation directe par le médecin déjà lié au patient. */
router.post("/:patientId/reconsult", requireAnyModule(...DOSSIER_MODULES), async (req, res) => {
  if (req.user!.role !== "MEDECIN") {
    return res.status(403).json({ error: "Réservé aux médecins" });
  }

  const patientId = String(req.params.patientId);
  const doctorId = req.user!.id;

  const patient = await prisma.patient.findUnique({
    where: { id: patientId },
    select: { id: true, category: true },
  });
  if (!patient) return res.status(404).json({ error: "Patient introuvable" });

  const linked = await prisma.visit.findFirst({
    where: { patientId, ...medecinMatchWhere(doctorId) },
    select: { id: true },
  });
  if (!linked) {
    return res.status(403).json({
      error: "Ce patient n'a pas encore été consulté par votre compte.",
    });
  }

  const activeVisit = await prisma.visit.findFirst({
    where: {
      patientId,
      status: { in: [VisitStatus.WAITING_CONSULTATION, VisitStatus.IN_CONSULTATION] },
      OR: [
        { assignedDoctorId: doctorId },
        { consultation: { is: { doctorId } } },
      ],
    },
    select: { id: true, status: true },
    orderBy: { updatedAt: "desc" },
  });

  if (activeVisit) {
    if (activeVisit.status === VisitStatus.WAITING_CONSULTATION) {
      await prisma.visit.update({
        where: { id: activeVisit.id },
        data: { status: VisitStatus.IN_CONSULTATION },
      });
    }
    return res.json({
      visitId: activeVisit.id,
      created: false,
      amountFcfa: 0,
      requiresPayment: false,
      message: "Visite en cours rouverte.",
    });
  }

  try {
    const plan = await planReconsultation(patientId);
    const renewal = await resolveConsultationFeeForPatientDoctor({
      patientId,
      doctorId,
      requestedAmount: null,
    });
    const billing = resolveConsultationBilling(patient.category, renewal.amountFcfa, 0);

    const visit = await prisma.$transaction(async (tx) => {
      if (plan.action === "create" && plan.archiveVisitIds.length) {
        await archiveVisitsForReconsultation(tx, plan.archiveVisitIds);
      }

      if (plan.action === "update") {
        const updated = await tx.visit.update({
          where: { id: plan.visitId },
          data: {
            status: VisitStatus.IN_CONSULTATION,
            assignedDoctorId: doctorId,
            consultationFeeFcfa: billing.consultationAmountFcfa || undefined,
            reductionFcfa: billing.reductionFcfa,
          },
        });

        if (billing.billableAmountFcfa > 0) {
          const existingInvoice = await tx.invoice.findFirst({
            where: { visitId: updated.id, type: InvoiceType.CONSULTATION },
          });
          if (!existingInvoice) {
            await tx.invoice.create({
              data: consultationInvoiceCreateData(patient.category, {
                invoiceNumber: await generateInvoiceNumber(),
                patientId,
                visitId: updated.id,
                amountFcfa: billing.billableAmountFcfa,
                issuedById: doctorId,
              }),
            });
          } else if (existingInvoice.status !== InvoiceStatus.PAID) {
            await tx.invoice.update({
              where: { id: existingInvoice.id },
              data: consultationInvoiceUpdateData(patient.category, billing.billableAmountFcfa),
            });
          }
        }

        return updated;
      }

      const created = await tx.visit.create({
        data: {
          patientId,
          status: VisitStatus.IN_CONSULTATION,
          assignedDoctorId: doctorId,
          consultationFeeFcfa: billing.consultationAmountFcfa || undefined,
          reductionFcfa: billing.reductionFcfa,
        },
      });

      if (billing.billableAmountFcfa > 0) {
        await tx.invoice.create({
          data: consultationInvoiceCreateData(patient.category, {
            invoiceNumber: await generateInvoiceNumber(),
            patientId,
            visitId: created.id,
            amountFcfa: billing.billableAmountFcfa,
            issuedById: doctorId,
          }),
        });
      }

      return created;
    });

    return res.status(201).json({
      visitId: visit.id,
      created: true,
      amountFcfa: billing.billableAmountFcfa,
      requiresPayment: billing.billableAmountFcfa > 0 && shouldCreateImmediateInvoice(patient.category),
      message: renewal.message ?? "Reconsultation ouverte.",
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "";
    if (message === "PATIENT_NOT_FOUND" || message === "DOCTOR_NOT_FOUND") {
      return res.status(400).json({ error: "Impossible d'ouvrir la reconsultation." });
    }
    return res.status(400).json({ error: "Impossible d'ouvrir la reconsultation." });
  }
});

router.post(
  "/:patientId/documents",
  requireAnyModule(...DOSSIER_MODULES),
  (req, res, next) => {
    upload.single("file")(req, res, (error) => {
      if (error instanceof multer.MulterError) {
        if (error.code === "LIMIT_FILE_SIZE") {
          return res.status(400).json({ error: "Fichier trop volumineux (max 15 Mo)" });
        }
        return res.status(400).json({ error: error.message });
      }
      if (error) {
        return res.status(400).json({ error: (error as Error).message });
      }
      next();
    });
  },
  async (req, res) => {
    const role = req.user!.role as AppUserRole;
    if (!canWriteDossierDocuments(role)) {
      return res.status(403).json({ error: "Accès refusé — consultation du dossier uniquement" });
    }

    const patientId = String(req.params.patientId);

    if (!req.file) {
      return res.status(400).json({ error: "Fichier requis" });
    }

    try {
      const body = uploadDocumentSchema.parse(req.body);
      const patient = await prisma.patient.findUnique({ where: { id: patientId } });
      if (!patient) {
        await fs.promises.unlink(req.file.path).catch(() => undefined);
        return res.status(404).json({ error: "Patient introuvable" });
      }

      const dossier = await ensurePatientDossier(patientId);
      const relativePath = path.relative(UPLOADS_ROOT, req.file.path);

      const document = await prisma.patientDocument.create({
        data: {
          dossierId: dossier.id,
          patientId,
          visitId: body.visitId,
          kind: body.kind,
          title: body.title.trim(),
          documentDate: new Date(body.documentDate),
          fileName: req.file.originalname,
          mimeType: req.file.mimetype,
          fileSize: req.file.size,
          storagePath: relativePath,
          uploadedById: req.user!.id,
        },
        include: {
          uploadedBy: { select: { firstName: true, lastName: true } },
        },
      });

      await prisma.auditLog.create({
        data: {
          userId: req.user!.id,
          action: "UPLOAD",
          entity: "PatientDocument",
          entityId: document.id,
          metadata: { patientId, kind: body.kind, title: body.title },
        },
      });

      return res.status(201).json(document);
    } catch {
      await fs.promises.unlink(req.file.path).catch(() => undefined);
      return res.status(400).json({ error: "Données invalides" });
    }
  },
);

router.get(
  "/:patientId/documents/:documentId/file",
  requireAnyModule(...DOSSIER_MODULES),
  async (req, res) => {
    const patientId = String(req.params.patientId);
    const documentId = String(req.params.documentId);

    if (req.user!.role === "MEDECIN") {
      const linkedToPatient = await prisma.visit.findFirst({
        where: { patientId, ...medecinMatchWhere(req.user!.id) },
        select: { id: true },
      });
      if (!linkedToPatient) {
        return res.status(403).json({ error: "Accès refusé — patient non suivi par votre compte." });
      }
    }

    const document = await prisma.patientDocument.findFirst({
      where: { id: documentId, patientId },
    });

    if (!document) return res.status(404).json({ error: "Document introuvable" });

    const absolutePath = path.join(UPLOADS_ROOT, document.storagePath);
    if (!fs.existsSync(absolutePath)) {
      return res.status(404).json({ error: "Fichier introuvable sur le serveur" });
    }

    res.setHeader("Content-Type", document.mimeType);
    res.setHeader(
      "Content-Disposition",
      `inline; filename="${encodeURIComponent(document.fileName)}"`,
    );

    return fs.createReadStream(absolutePath).pipe(res);
  },
);

router.delete(
  "/:patientId/documents/:documentId",
  requireAnyModule(...DOSSIER_MODULES),
  async (req, res) => {
    const role = req.user!.role as AppUserRole;
    if (!canWriteDossierDocuments(role)) {
      return res.status(403).json({ error: "Accès refusé — droits de gestion requis" });
    }

    const patientId = String(req.params.patientId);
    const documentId = String(req.params.documentId);

    const document = await prisma.patientDocument.findFirst({
      where: { id: documentId, patientId },
    });

    if (!document) return res.status(404).json({ error: "Document introuvable" });

    try {
      await assertPatientDataDeletable(patientId);
    } catch {
      return res.status(409).json({ error: PATIENT_HAS_PAYMENTS_MESSAGE });
    }

    await deleteDocumentFile(document.storagePath);
    await prisma.patientDocument.delete({ where: { id: document.id } });

    await prisma.auditLog.create({
      data: {
        userId: req.user!.id,
        action: "DELETE",
        entity: "PatientDocument",
        entityId: document.id,
        metadata: { patientId, kind: document.kind, title: document.title },
      },
    });

    return res.json({ ok: true });
  },
);

export async function initPatientDossiers() {
  await ensureUploadsRoot();
  const count = await backfillMissingDossiers();
  if (count > 0) {
    console.log(`${count} dossier(s) patient créé(s) pour les patients existants.`);
  }
}

export default router;
